### ISSUE TITLE
Sort imports

### ISSUE THREAD

**Issue by vllcrz** [keybas-engineering/eslint-config-backend#2]
On peut utiliser le plugin [eslint-plugin-import](https://github.com/import-js/eslint-plugin-import), qui définit entre autres une règle [`import/order`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md) qui permet de définir un ordre d'imports.

Question : quel ordre privilégier ? (c'est du détail mais c'est bien de prendre une décision.)

J'aurais tendance à mettre les types en premier, mais je vois beaucoup de gens mettre les types à la fin.

**Comment by vllcrz** [comment]
D'après la doc, il faut installer à la fois le `eslint-plugin-import`, et le [`eslint-import-resolver-typescript`](https://github.com/alexgorbatchev/eslint-import-resolver-typescript) (qu'il faut configurer).

Ensuite on peut étendre les deux configurations `plugin:import/recommended` et `plugin:import/typescript`, et après tout est ok (on peut définir nos propres rules d'ordre d'imports et d'autres choses si on le souhaite, et ça devrait fonctionner).

**Comment by KB-MaxCh** [comment]
Perso, je n'a pas de référence sur le fait qu'on ait les imports de type en premier ou derrière les imports classique. Par contre, il ne faudrait pas qu'ils se mélangent. Et peut être, prévoir un espace entre ces 2 blocs d'import, si c'est pas trop compliqué.

**Comment by KB-MaxCh** [comment]
Est ce qu'on peut aussi avoir l'effacement automatique des imports inutilisés dans le module ? Ca serait trop bien d'avoir tout ca (tri et effacement ) quand on save le fichier.

**Comment by vllcrz** [comment]
@KB-MaxCh actuellement ESLint détecte les imports inutilisés avec la règle `@typescript-eslint/no-unused-vars`, qui ne gère pas l'auto-fix. Avec le plugin [eslint-plugin-unused-imports](https://www.npmjs.com/package/eslint-plugin-unused-imports) configuré correctement, ça devrait pouvoir être auto-fixable.

Après être tombé sur [cette réponse stackoverflow](https://stackoverflow.com/a/68016089), j'ai rajouté cette petite configuration dans le `settings.json` de mon VS Code, et c'est excellent :

```json
{
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
  "eslint.validate": ["javascript", "typescript"]
}
```
